app/models.py
from dataclasses import dataclass
from app import db
from sqlalchemy import Sequence
import datetime

# Product Class/Model
@dataclass
class Product(db.Model):
    id: int
    name: str
    category: str
    price: float
    qty: int
    subcategory: str

    __tablename__ = 'product'
    id = db.Column(db.Integer, Sequence('seq_product'), primary_key=True)
    name = db.Column(db.String(100), unique=True)
    category = db.Column(db.String(200))
    price = db.Column(db.Float)
    qty = db.Column(db.Integer)
    subcategory = db.Column(db.String(100))

    def __init__(self, name, category, price, qty, subcategory):
        self.name = name
        self.category = category
        self.price = price
        self.qty = qty
        self.subcategory = subcategory

    def __repr__(self):
        return '<Product {id}>'.format(id=self.id)


# Shop Class/Model
@dataclass
class Shop(db.Model):
    id: int
    owner: str
    city: str
    segment: str
    address: str
    lat: float
    long: float

    __tablename__ = 'shop'
    id = db.Column(db.Integer, Sequence('seq_shop'), primary_key=True)
    owner = db.Column(db.String)
    city = db.Column(db.String)
    segment = db.Column(db.String)
    address = db.Column(db.String)
    lat = db.Column(db.Float)
    long = db.Column(db.Float)

    def __init__(self, owner, city, segment, address, lat, long):
        self.owner = owner
        self.city = city
        self.segment = segment
        self.address = address
        self.lat = lat
        self.long = long

    def __repr__(self):
        return '<Shop {id}>'.format(id=self.id)


# Receipt Class/Model
@dataclass
class Receipt(db.Model):
    id: int
    shop_id: int
    datetime: datetime.datetime
    product_id: int
    value: float
    qty: float

    __tablename__ = 'receipt'
    id = db.Column(db.Integer, Sequence('seq_receipt'), primary_key=True)
    shop_id = db.Column(db.Integer, db.ForeignKey('shop.id'), nullable=False)
    datetime = db.Column(db.DateTime, nullable=False)
    product_id = db.Column(db.Integer, db.ForeignKey('product.id'), nullable=False)
    value = db.Column(db.Float, nullable=False)
    qty = db.Column(db.Float, nullable=False)

    def __init__(self, shop_id, datetime, product_id, value, qty):
        self.shop_id = shop_id
        self.datetime = datetime
        self.product_id = product_id
        self.value = value
        self.qty = qty

    def __repr__(self):
        return '<Receipt {id}>'.format(id=self.id)

    def __iter__(self):
        iters = dict((x, y) for x,y in Receipt.__dict__.items() if x[:2] != '__')
        iters.update(self.__dict__)
        for x, y in iters.items():
            yield x, y

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, IntegerField, FloatField
from wtforms.validators import DataRequired, ValidationError, Length
from flask import request


class EditShopForm(FlaskForm):
    owner = StringField('Owner', validators=[DataRequired()])
    city = StringField('City', validators=[DataRequired()])
    segment = StringField('Segment')
    address = StringField('Street, number', validators=[DataRequired()])
    lat = FloatField('Latitude')
    long = FloatField('Longtitude')
    submit = SubmitField('Submit')


class EditProductForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    category = StringField('Category', validators=[DataRequired()])
    price = FloatField('Price', validators=[DataRequired()])
    qty = FloatField('Quantity', validators=[DataRequired()])
    subcategory = StringField('Subcategory', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask, current_app
from flask_sqlalchemy import SQLAlchemy
from config import Config
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap
import os


db = SQLAlchemy()
migrate = Migrate()
bootstrap = Bootstrap()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    db.init_app(app)
    migrate.init_app(app, db, compare_type=True)
    bootstrap.init_app(app)

    from app.api import bp as api_bp
    app.register_blueprint(api_bp, url_prefix='/api')

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    return app

from app import models

app/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__)

from app.api import routes

app/api/routes.py
from flask import jsonify, render_template, url_for, request, current_app
from app.api import bp
from app.models import Product, Shop

# Get All Products
@bp.route('/product', methods=['GET'])
def get_products():
    all_products = Product.query.all()
    return jsonify(all_products)


@bp.route('/shop', methods=['GET'])
def get_shops():
    all_shops = Shop.query.all()
    return jsonify(all_shops)

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main',__name__)

from app.main import routes

app/main/routes.py
from flask import jsonify, render_template, url_for, request, current_app, redirect, Response
from app import db, create_app
from app.main import bp
from app.models import Product, Shop, Receipt
from app.main.forms import EditShopForm, EditProductForm
import json
from kafka import KafkaConsumer
import ast


@bp.route('/', methods=['GET','POST'])
@bp.route('/index', methods=['GET', 'POST'])
def index():
    return render_template('index.html', title='Home')


@bp.route('/shop', methods=['GET', 'POST'])
def shop():
    form = EditShopForm()
    if form.validate_on_submit():
        shop = Shop(owner=form.owner.data, city=form.city.data, segment=form.segment.data, address=form.address.data,
                    lat=form.lat.data, long=form.long.data)
        db.session.add(shop)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('shop.html', title='Shop', form=form)


@bp.route('/product', methods=['GET', 'POST'])
def product():
    form = EditProductForm()
    if form.validate_on_submit():
        product = Product(name=form.name.data, category=form.category.data, price=form.price.data
                          , qty=form.qty.data, subcategory=form.subcategory.data)
        db.session.add(product)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('product.html', title='Product', form=form)


@bp.route('/receipt', methods=['GET', 'POST'])
def receipt():
    return render_template('receipt.html', title='Receipt')


@bp.route('/dashboard', methods=['GET'])
def dashboard():
    return render_template('dashboard.html', title='Dashboards')


@bp.route('/chart-data')
def chart_data():
    consumer = KafkaConsumer('numtest', bootstrap_servers=['localhost:9092'], auto_offset_reset='earliest',
                             enable_auto_commit=True, group_id='my-group-flask',
                             value_deserializer=lambda x: json.loads(x.decode('utf-8')))

    def generate_random_data():
        for message in consumer:
            message = message.value
            data = ast.literal_eval(message)
            receipt = Receipt(data.get('shop_id'), data.get('datetime'), data.get('product_id'), data.get('value'),
                              data.get('qty'))
            json_data = json.dumps({'time': receipt.datetime, 'value': receipt.value, 'shop_id': receipt.shop_id})
            yield f"data:{json_data}\n\n"

    return Response(generate_random_data(), mimetype='text/event-stream')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="static/assets/ico/favicon.ico">
    <title>Datashop</title>

    <!-- Bootstrap core CSS -->
    <link href="static/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="static/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    <link href="static/assets/css/carousel.css" rel="stylesheet">
  </head>
<!-- NAVBAR
================================================== -->
  <body>
    <div class="navbar-wrapper">
      <div class="container">

        <div class="navbar navbar-inverse navbar-static-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{{ url_for('main.index') }}">Datashop concept</a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="{{ url_for('main.index') }}">Home</a></li>
                <li><a href="{{ url_for('main.shop') }}">Shop</a></li>
                <li><a href="{{ url_for('main.product') }}">Product</a></li>
                <li><a href="{{ url_for('main.receipt') }}">Receipt</a></li>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </div>

    {% block content %}
    <div class="container">
        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
    {% endblock %}

        <!-- FOOTER -->
      <footer>
		<div class="container">
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2021 Datashop . &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
		</div>
      </footer>



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="static/dist/js/bootstrap.min.js"></script>
    <script src="static/assets/js/holder.js"></script>
  </body>
</html>

app/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Creating Real-Time Charts with Flask</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <canvas id="canvas"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>
<!--suppress JSUnresolvedLibraryURL -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<!--suppress JSUnresolvedLibraryURL -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!--suppress JSUnresolvedLibraryURL -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>

<script>
    $(document).ready(function () {
        const config = {
            type: 'line',
            data: {
                labels: [],
                datasets: [{
                    label: "Random Dataset",
                    backgroundColor: 'rgb(255, 99, 132)',
                    borderColor: 'rgb(255, 99, 132)',
                    data: [],
                    fill: false,
                }],
            },
            options: {
                responsive: true,
                title: {
                    display: true,
                    text: 'Real time sales'
                },
                tooltips: {
                    mode: 'index',
                    intersect: false,
                },
                hover: {
                    mode: 'nearest',
                    intersect: true
                },
                scales: {
                    xAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Time'
                        }
                    }],
                    yAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Value'
                        }
                    }]
                }
            }
        };

        const context = document.getElementById('canvas').getContext('2d');

        const lineChart = new Chart(context, config);

        const source = new EventSource("/chart-data");

        source.onmessage = function (event) {
            const data = JSON.parse(event.data);
            if (config.data.labels.length === 20) {
                config.data.labels.shift();
                config.data.datasets[0].data.shift();
            }
            config.data.labels.push(data.shop_id);
            config.data.datasets[0].data.push(data.value);
            lineChart.update();
        }
    });
</script>
</body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block app_content %}
	<div class="mainTitle">
	<div class="container">
	<h1>Datashopper</h1>
	<p>
	</p>
	</div>
	</div>

    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">
      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <img class="img-circle" src="static/assets/images/nepali-momo.png" alt="Generic placeholder image">
          <h2>Nepalese MOMO</h2>
          <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies</p>
          <p><a class="btn btn-default" href="#" role="button">&pound; 2.2 Add to cart &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="static/assets/images/burger.png" alt="Generic placeholder image">
          <h2>Burger</h2>
          <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. </p>
          <p><a class="btn btn-default" href="#" role="button">&pound;5 Add to cart &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
		  <img class="img-circle" src="static/assets/images/gorkha-special-chicken.png" alt="Lam Tikka">
          <h2>Gurkha Chicken</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. </p>
          <p><a class="btn btn-default" href="#" role="button">&pound;4 Add to cart &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->
	</div>
{% endblock %}

app/templates/product.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Here you can add data about products to database. Please fill the form</h1>
    <p>
    </p>
    <div class="row">
        <div class="col-md-4">
            <p>
                    <form action="{{ url_for('main.product') }}" method="post">
                        {{ wtf.quick_form(form) }}
                    </form>
            </p>
        </div>
    </div>
{% endblock %}

app/templates/receipt.html
{% extends "base.html" %}

{% block app_content %}
<script src="https://js.api.here.com/v3/3.1/mapsjs-core.js" type="text/javascript" charset="utf-8"></script>
<script src="https://js.api.here.com/v3/3.1/mapsjs-service.js" type="text/javascript" charset="utf-8"></script>

<h1>Hello World!</h1>
<p>
<h1>Hello World!</h1>
</p>
<p>
<h1>Hello World!</h1>
</p>
<p>
<h1>Hello World!</h1>
</p>


{% endblock %}

app/templates/shop.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Here you can add data about your shops. Please fill the form</h1>
    <p>
    </p>
    <div class="row">
        <div class="col-md-4">
            <p>
                    <form action="{{ url_for('main.shop') }}" method="post">
                        {{ wtf.quick_form(form) }}
                    </form>
            </p>
        </div>
    </div>
{% endblock %}